apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd-example
  name: httpd-example
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd-example
  template:
    metadata:
      labels:
        app: httpd-example
    spec:
      containers:
      - image: httpd
        name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
